workspace:
  base: /go
  path: src/github.com/vallard/drone-kube

pipeline:
  build:
    image: golang:1.6-alpine
    environment:
      - CGO_ENABLED=0
    commands:
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  deploy:
    image: plugins/docker
    repo: benschumacher/drone-kube
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Kube
  desc: Update Deployments on kubernetes
  type: deploy
  image: vallard/drone-kube
